# 服务配置
server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 50
    accept-count: 10

# 应用配置
app:
  config:
    api-version: v1
    cross-origin: '*'

# 线程池
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# MySQL
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: userId
      list: db01,db02

      db00:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/big_market
        username: root
        password: jason2004
        type-class-name: com.zaxxer.hikari.HikariDataSource
        pool:
          pool-name: Retail_HikariCP
          minimum-idle: 15
          idle-timeout: 180000
          maximum-pool-size: 25
          auto-commit: true
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1

      db01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/big_market_01
        username: root
        password: jason2004
        type-class-name: com.zaxxer.hikari.HikariDataSource
        pool:
          pool-name: Retail_HikariCP
          minimum-idle: 15
          idle-timeout: 180000
          maximum-pool-size: 25
          auto-commit: true
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1

      db02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/big_market_02
        username: root
        password: jason2004
        type-class-name: com.zaxxer.hikari.HikariDataSource
        pool:
          pool-name: Retail_HikariCP
          minimum-idle: 15
          idle-timeout: 180000
          maximum-pool-size: 25
          auto-commit: true
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1

# MyBatis
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Redis
redis:
  sdk:
    config:
      password: jason2004
      host: 127.0.0.1
      port: 6379
      database: 1
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# RabbitMQ
spring:
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: dasi
    password: jason2004
    listener:
      simple:
        retry:
          enabled: false
        prefetch: 1
    topic:
      recharge_sku_stock_empty: recharge_sku_stock_empty
      dispatch_activity_award: dispatch_activity_award
      dispatch_behavior_reward: dispatch_behavior_reward
      dispatch_trade_outcome: dispatch_trade_outcome