version: "3.9"

networks:
  big-market:

services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "jason2004"
    volumes:
      - ${HOME}/docker/mysql/data:/var/lib/mysql
      - ${HOME}/docker/mysql/conf:/etc/mysql/conf.d
      - ${HOME}/docker/mysql/logs:/logs
    networks:
      - big-market

  redis:
    image: redis:8.0.1
    container_name: redis
    restart: always
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "jason2004"
    ]
    ports:
      - "6379:6379"
    volumes:
      - ${HOME}/docker/redis/data:/data
    networks:
      - big-market

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: dasi
      RABBITMQ_DEFAULT_PASS: "jason2004"
    volumes:
      - ${HOME}/docker/rabbitmq/data:/var/lib/rabbitmq
      - ${HOME}/docker/rabbitmq/log:/var/log/rabbitmq
      - ${HOME}/docker/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez
    networks:
      - big-market
    command: >
      bash -c "
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-server
      "